version: "3.9"
services:
  backend:
    build: ./server
    container_name: newsblog-backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    command: ["npm", "start"]   

  frontend:
    build: ./client
    container_name: newsblog-frontend
    restart: always
    ports:
      - "3000:80"

  mongo:
    image: mongo:6.0
    container_name: newsblog-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
